### PR TITLE
Bug fixes

### LINKED ISSUE #3: Nav bar: buggy routing on pages aside Landing page
On the CFP page, when clicking on any of the navs in the header, it does not route them to the particular section on the Landing page. 
We need to fix this!

### LINKED ISSUE #7: Failed Build
The app built successfully locally, but failed on Vercel with the following log:

```
Failed to compile.
./src/app/hero.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[13].oneOf[10].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[13].oneOf[10].use[3]!./src/app/hero.css
Error: Cannot find module '@tailwindcss/postcss'
Require stack:
- /vercel/path0/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js
- /vercel/path0/node_modules/next/dist/build/webpack/config/blocks/css/index.js
- /vercel/path0/node_modules/next/dist/build/webpack/config/index.js
- /vercel/path0/node_modules/next/dist/build/webpack-config.js
- /vercel/path0/node_modules/next/dist/build/webpack-build/impl.js
- /vercel/path0/node_modules/next/dist/compiled/jest-worker/processChild.js
    at Function.<anonymous> (node:internal/modules/cjs/loader:1225:15)
    at /vercel/path0/node_modules/next/dist/server/require-hook.js:55:36
    at Function.resolve (node:internal/modules/helpers:146:19)
    at loadPlugin (/vercel/path0/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:49:32)
    at /vercel/path0/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:157:56
    at Array.map (<anonymous>)
    at getPostCssPlugins (/vercel/path0/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:157:47)
    at async /vercel/path0/node_modules/next/dist/build/webpack/config/blocks/css/index.js:124:36
    at async /vercel/path0/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js:52:40
    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:153:20)
Import trace for requested module:
./src/app/hero.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[13].oneOf[10].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[13].oneOf[10].use[3]!./src/app/hero.css
./src/app/hero.css
./src/pages/landing-page.tsx
./src/styles/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[13].oneOf[10].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[13].oneOf[10].use[3]!./src/styles/globals.css
Error: Cannot find module '@tailwindcss/postcss'
```

Basically, Cannot find module '@tailwindcss/postcss'

### PR DESCRIPTION
**Pull request by nutcas3**
fix #3 
fixes #7 to

### CODE REVIEW

**Comment by D-sense** [comment]
Thanks for looking into this!
I will be able to review it and hopefully merge it once we sort out the build issue mentioned #7

**Comment by nutcas3** [comment]
> Thanks for looking into this! I will be able to review it and hopefully merge it once we sort out the build issue mentioned #7

Hello sorted the build issue kindly try noe

**Comment by D-sense** [comment]
Let's have the fix in a separate PR; just in case something goes wrong, we can easily revert the PR without undoing the navbar routing fix

**Comment by nutcas3** [comment]
Hello @D-sense I think here its okay I have already done the fix 
image

File: src/components/hero/Hero.tsx [hunk 1]
```diff
@@ -65,9 +65,9 @@ export default function Hero() {
                 Get your ticket
                 <ChevronRight className="w-6 h-6 ml-2 group-hover:translate-x-1 transition-transform" />
               </Link>
-              <Link href={paths.callForSpeakers()} className="border-2 border-white hover:border-white text-white px-8 py-4 rounded-full font-bold text-lg transition-all hover:bg-white/20 backdrop-blur-xs">
+              <a href={paths.callForSpeakers()} className="border-2 border-white hover:border-white text-white px-8 py-4 rounded-full font-bold text-lg transition-all hover:bg-white/20 backdrop-blur-xs">
```
Comment (D-sense) [inline src/components/hero/Hero.tsx:68]: What issue do you intend to solve with this change?

Comment (nutcas3) [reply src/components/hero/Hero.tsx:68]: this one was the issue with nagigation actually since its not pages the Link is not used for it 
Just test it out 
Funny enough that's how Next approaches Naviagtion in the pages and to other pages where you have to use LInke

Comment (nutcas3) [reply src/components/hero/Hero.tsx:68]: Just check usage of <a/> is usuay for in page components while <Link/> is for pages

**Review by D-sense — APPROVED** [review]
LGTM
